# Generated by Django 5.1.6 on 2025-03-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message'),
    ]

    operations = [
    ]
